export const featherpeacockrewards = [
  {
    id: 1,
    featherrew: 'Feather of Joy!',
    featherdesc: `You get it for the first opened feather with a joke.`,
    featherim: require('../../assets/images/featherrew1.png'),
    featheriminact: require('../../assets/images/featherrew1in.png'),
    featherunlocked: false,
  },
  {
    id: 2,
    featherrew: 'Feather of Laughter',
    featherdesc: 'For 10 opened jokes in the "Tail of Humor"',
    featherim: require('../../assets/images/featherrew2.png'),
    featheriminact: require('../../assets/images/featherrew2in.png'),
    featherunlocked: false,
  },
  {
    id: 3,
    featherrew: 'Feather of the Sun',
    featherdesc: 'For opening a feather every day for 7 days in a row.',
    featherim: require('../../assets/images/featherrew3.png'),
    featheriminact: require('../../assets/images/featherrew3in.png'),
    featherunlocked: false,
  },
  {
    id: 4,
    featherrew: 'Feather of Mood',
    featherdesc: 'For the first time sharing a joke with a friend.',
    featherim: require('../../assets/images/featherrew4.png'),
    featheriminact: require('../../assets/images/featherrew4in.png'),
    featherunlocked: false,
  },
  {
    id: 5,
    featherrew: 'Feather of Collector',
    featherdesc: 'For opening 25 different jokes.',
    featherim: require('../../assets/images/featherrew5.png'),
    featheriminact: require('../../assets/images/featherrew5in.png'),
    featherunlocked: false,
  },
  {
    id: 6,
    featherrew: 'Feather of Gold',
    featherdesc: `It's given when you read 50 jokes and become the real master of the "Tail of Humor."`,
    featherim: require('../../assets/images/featherrew6.png'),
    featheriminact: require('../../assets/images/featherrew6in.png'),
    featherunlocked: false,
  },
];
