export const featherpeacocktails = [
  `Why doesn't a peacock take out a loan? Because its tail is already a "gold card".`,
  `A goose is always serious... because no one has told it that life is a meme yet.`,
  `A peacock opened its tail and says: "This is not pathos, this is natural Wi-Fi".`,
  `A duck is late for a date: "Sorry, I got stuck at the pond".`,
  `The turkeys created a band and called it: "Gobble Trouble".`,
  `Why are pigeons always in the city? Because there is Wi-Fi without a password there.`,
  `A peacock doesn't like winter jackets - its tail doesn't fit.`,
  `A goose always quarrels because no one repeats its "goose" step.`,
  `Why are ducks cooler? Because they are always on a "crap show".`,
  `A peacock in the mirror: "Well, handsome, are you ready to shine again?"`,
  `Why is a turkey afraid of November? Because Thanksgiving is there.`,
  `Goose in a bar: “I need still water, I’m on a diet.”`,
  `Peacock at a party: “I don’t dance — I show my tail.”`,
  `Duck always keeps up with the news… because it quacks loudly.`,
  `Why isn’t a peacock a card player? Because its tail gives away all the “trump cards.”`,
  `Goose gets angry: “Don’t just call me a goose, I’m a VIP Bird.”`,
  `Turkeys came up with a TikTok challenge: “Gobble Dance.”`,
  `Duck in a store: “I need a loaf and a bag for quacking.”`,
  `Peacock says: “I’m not just a bird, I’m a walking firework.”`,
  `Why is a goose always in the spotlight? Because it’s the noisiest of all.`,
  `Duck doesn’t take a taxi — I’ve had enough of it.`,
  `Turkeys put together a rap battle: “Gobble vs Wobble.”`,
  `Peacock doesn’t like rain — he makes “wet art” out of his tail.`,
  `Goose always looks angry, but really wants a hug.`,
  `Why can ducks swim? Because they can't "google".`,
  `Peacock goes to work: "My dress code is always WOW".`,
  `Turkeys want to go to the movies, but they only get the role of lunch.`,
  `Goose opened a gym: "Walk straight, like me!"`,
  `Duck always has a phone with him - to quack to his friends.`,
  `Peacock asks: "So how do you like my Instagram tail?"`,
  `Why do pigeons always hang out in the square? Because there is "free grain".`,
  `Turkeys came up with meditation: "Inhale - gobble, exhale - gobble".`,
  `Goose on a date: "My main feature is stubbornness".`,
  `Peacock: "Don't look at me like a picture... I'm animation".`,
  `Duck at night: “Quiet, quack, quack” — neighbors: “Quiet, we’re sleeping!”`,
  `Why is the peacock proud? Because even the rainbow is jealous of its colors.`,
  `Turkeys have built a coffee shop: “Gobble Latte”.`,
  `Goose: “I’m not aggressive, I just love loudly”.`,
  `Duck at a party: “I’m here for the music… and bread”.`,
  `Peacock opened its tail again — people thought it was a new art object.`,
  `Why doesn’t the turkey eat chips? Because it’s afraid of crumbs on its tail.`,
  `Goose sings in the shower — and all the neighbors are awake.`,
  `Duck in a restaurant: “I’ll have a salad and some quack-quack sauce”.`,
  `Peacock in a selfie: “I can’t fit in the frame, it’s the tail’s fault again”.`,
  `Turkeys have come up with a startup: “GobbleCoin”.`,
  `The goose always wins the race because it shouts at its rivals.`,
  `The duck: “I’m not funny… I’m just really cool.”`,
  `The peacock: “My tail is Photoshop in real life.”`,
  `The goose doesn’t play chess because all the pieces run away.`,
  `The turkeys at karaoke: “Gobble me maybe!” 🎤`,
];
