export const featherpeacockdlfeathrs = [
  `Why doesn’t the peacock go to the gym? Because his tail is always pumped up!`,
  `The duck asks the turkey: “Well, bro, when are we going to sing a duet?” — “Not on Thanksgiving.”`,
  `Why is the goose always serious? Because his beak doesn’t allow him to laugh.`,
  `Why is the turkey always proud? Because his tail is like Wi-Fi: everyone is watching, but they can’t connect.`,
  `The peacock opened his tail and said: “I’m into design!”`,
  `Why does the rooster always crow in the morning? Because he doesn’t have an alarm clock.`,
  `The goose asks the duck: “Why do you always quack?” — “Because that’s how I express my emotions!”`,
  `Why doesn’t the turkey sing? Because his rap style is “gobble-gobble.”`,
  `A peacock enters a bar: “Do you have a bigger mirror? I want to check my tail!”`,
  `Why did the chicken cross the road? To see how the peacock would do it.`,
  `A goose goes to the theater. They tell him: “Perform beautifully!” — “I’m going, I’m already handsome!”`,
  `Why does a duck like water? Because without Wi-Fi, that’s the only place you can have fun.`,
  `Peacock: “Don’t look me in the eyes!” — “But I’m looking at my tail…”`,
  `Why is a turkey always cheerful? Because its tail works like a firework.`,
  `Peacock in front of the mirror: “So, handsome, are you ready for a party?”`,
  `A goose asks a duck: “Why don’t you fly?” — “I’m a VIP, they’re taking me!”`,
  `Why doesn’t a peacock play cards? Because it always opens its tail — and everyone can see what it has.`,
  `The turkeys have come up with a band. Name: “Gobble Beat.”`,
  `A duck in a store: “I need a pack of chips, and I’ll quack the rest!”`,
  `Why doesn’t a peacock take an umbrella? Because its tail is always with it.`,
  `A goose at a disco: “Turn on slow-motion, I want to walk beautifully!”`,
  `A duck in front of a mirror: “Am I a model or just a quack?”`,
  `Why is a turkey proud? Because even Google can’t repeat its sound.`,
  `A peacock met a pigeon: “Hey, brother, at least add some color!”`,
  `Why is a goose always angry? Because everyone laughs at its “goose” step.`,
  `A peacock: “I don’t dance — I just spread my tail.”`,
  `Turkeys have invented a new diet: “eat everything, but only until Thanksgiving.”`,
  `A duck asks: “Why is everyone shouting “quack-quack” at me?” — ​​“Because you started it yourself.”`,
  `The peacock ends the day: "The main thing is that the tail remains beautiful, and the rest is trifles."`,
];
